---
title: "SOC3070 Análisis de Datos Categóricos"
author: "Tarea corta 2, respuestas"
output:
  pdf_document: default
urlcolor: blue
linkcolor: red

---

```{r, echo=FALSE}
# Escribir install.packages("tinytex") en la consola para instalar "tinytex"
# Carga "tinytex" para compilar PDF
library("tinytex")
```

Ponderación: 6% de la nota final del curso.


En esta pregunta aplicarán propiedades de probabilidades condicionales y el teorema de Bayes para calcular alguna cantidades de interés en tiempos de pandemia. 

### Problema

Preocupado por la presencia de síntomas anómalos decides tomarte un test pcr para determinar si tienes Covid-19 o no. Luego de un día de espera el test $pcr$ arroja que eres Covid positivo. Este resultado es preocupante dado que un paper que leiste en [The Lancet](https://www.thelancet.com) indica que:

- La "sensibilidad" del test es de 90\% (probabilidad de que una persona con la enfermedad obtenga un test positivo). 
- La tasa de falsos positivos del test es de 5\% (probabilidad que una persona sin la enfermedad obtenga un test positivo).
- La prevalencia de la enfermedad es de un 7\% (probabilidad de que una persona presente la enfermedad).

### Pregunta

Conociéndo toda esta información ¿Cuál es la probabilidad de que realmente tengas Covid-19?

### Respuesta:

La cantidad de interés es la siguiente probabilidad condicional:

$$\mathbb{P}(\text{Covid} \mid  \text{pcr positivo})$$
Usando el Teorema de Bayes obtenemos que:

$$\mathbb{P}(\text{Covid} \mid  \text{pcr positivo}) = \frac{\mathbb{P}(\text{pcr positivo} \mid \text{Covid})\mathbb{P}(\text{Covid})}{\mathbb{P}(\text{pcr positivo})}$$
Usando la ley de probabilidad total podemos re-expresar el denominador en el lado derecho de la ecuación de la siguiente forma:


$$\mathbb{P}(\text{Covid} \mid  \text{pcr positivo}) = \frac{\mathbb{P}(\text{pcr positivo} \mid \text{Covid})\mathbb{P}(\text{Covid})}{\mathbb{P}(\text{pcr positivo} \mid \text{Covid})\mathbb{P}(\text{Covid}) + \mathbb{P}(\text{pcr positivo} \mid \neg \text{Covid})\mathbb{P}(\neg\text{Covid})}$$

Reemplazando las expresiones arriba con las cifras reportadas por [The Lancet](https://www.thelancet.com) obtenemos que:


$$\mathbb{P}(\text{Covid positivo} \mid  \text{pcr positivo}) = \frac{0.9 \times 0.07}{0.9 \times 0.07 + 0.05 \times 0.93} = 0.575 $$
Es decir, la probabilidad de que una persona con un test pcr positivo efectivamente tenga Covid-19 es de aproximádamente 58\%.



